import { readdir, readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dist = path.join(root, 'dist');
const files = await readdir(dist);
if (files.length !== 1 || files[0] !== '_routes.json') throw new Error('Unexpected public asset in dist');
const routes = JSON.parse(await readFile(path.join(dist, '_routes.json'), 'utf8'));
if (JSON.stringify(routes) !== JSON.stringify({ version: 1, include: ['/*'], exclude: [] })) throw new Error('Invalid API routing boundary');
console.log('Verified: API-only dist, no website, extension, data or secrets');
